### ISSUE TITLE
[HELP] rules in stylelintrc conflict with prettierrc

### ISSUE THREAD

**Issue by max8hine** [prettier/stylelint-prettier#9]
**Version:**
prettier: 1.14.2
stylelint: 9.6.0
stylelint-prettier: 1.0.3
stylelint-config-prettier: 4.0.0

**.stylelintrc**
``` json
{
  "plugins": ["stylelint-prettier"],
  "extends": "stylelint-config-recommended",
  "rules": {
    "prettier/prettier": [
      true,
      {
        "singleQuote": false
      }
    ]
  }
}
```
**.prettierrc**
``` json
{
  "singleQuote": true,
}

```

**What source code are you linting?**
``` css
.alter:after {
  color: red;
  content: "example"; // <- show not conver to single quotes
}
```

**What did you expect to happen?**
should not remove the double quotes in CSS string on editor save.

**What actually happened?**
removed double quotes in CSS sting on editor save, and added single quotes. I guess that *.prettierrc* has a rule `single quote` that actually for Javascript files.
